import Head from "next/head";
import Header from "@/common/components/Header";
import Footer from "@/common/components/Footer";
import AboutMe from "@/common/components/AboutMe";
import Skills from "@/common/components/Skills";
import Projects from "@/common/components/Projects";
import React from "react";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={'container'}>
        <AboutMe/>
        <Skills/>
        <Projects/>
      </main>
      <Footer/>
    </>
  );
}
